ci: pin torch version (#10185)
* ci: pin torch version

i think this should work. I need to spin up a linux instance locally to test this but I wanted to see what it looks like in CI

* chore: address rabbit

* use direct reference

I tried to avoid this but this seems to be the only solution that works locally. lets see what happens in ci

* add pinned versions for all python versions

* change index order

* chore: address coderabbit windows comment

* chore: add aarch64 support

* chore: add win32 support

* chore: add missing cpu to win32

* retry +cpu on ci not local

* index not in deperate config

* chore: revert to my solution

revert to the ugly solution I found yesterday

* chore: try unpinning other deps

other deps that are pinned are causing problems if we remove them we can possibly make the torch dep more readable

* chore: revert

* chore: index no name +cpu dep

* chore: test index-strategy = "unsafe-best-match"

* chore: revert to og solution + remove network pin

* chore: reorger index and +cpu

* chore: remove name

* chore: revert to my og solution

* chore: test jordan comments

test what happens if we remove "torch==2.8.0; sys_platform == 'darwin'"
and
index = [
    { url = "https://pypi.org/simple"},
    { url = "https://download.pytorch.org/whl/cpu"}]

* chore: re-add allow-direct-references

dont know how but i read it ass `index-strategy = "unsafe-best-match"` and removed it

`allow-direct-references` necessary to allow the direct referencing we are using wth for the torch dependencies with out it hatchling returns the below error

Call to `hatchling.build.build_editable` failed (exit status: 1)
...
line 1205, in dependencies_complex
          raise ValueError(message)
      ValueError: Dependency #106 of field `project.dependencies`
      cannot be a direct reference unless field
      `tool.hatch.metadata.allow-direct-references` is set to `true`

      hint: This usually indicates a problem with the package or the build
      environment.
Error: Process completed with exit code 1.

* chore: update uv.lock

---------

Co-authored-by: Adam Aghili <Adam.Aghili@ibm.com>