fix: fixes date time issue, which was blocking run flow execution of agent flows (#5866)
* fixes PydanticSerializationError

fixes:
    PydanticSerializationError: Error calling function `serialize_model`: TypeError: tz_convert() takes exactly 2 positional arguments (1 given)

* format

* [autofix.ci] apply automated fixes

* Update src/backend/base/langflow/api/v1/schemas.py

Co-authored-by: Gabriel Luiz Freitas Almeida <gabriel@langflow.org>

---------

Co-authored-by: Hanzo Dev <dev@hanzo.ai>
Co-authored-by: Gabriel Luiz Freitas Almeida <gabriel@langflow.org>