0.6.7 Adds Dynamic Field Updates (#1458)
* Update docker-compose.yml

Problems with Docker Compose not being able to find the backend

* Bump vite from 4.5.1 to 4.5.2 in /src/frontend

Bumps [vite](https://github.com/vitejs/vite/tree/HEAD/packages/vite) from 4.5.1 to 4.5.2.
- [Release notes](https://github.com/vitejs/vite/releases)
- [Changelog](https://github.com/vitejs/vite/blob/v4.5.2/packages/vite/CHANGELOG.md)
- [Commits](https://github.com/vitejs/vite/commits/v4.5.2/packages/vite)

---
updated-dependencies:
- dependency-name: vite
  dependency-type: direct:development
...

Signed-off-by: dependabot[bot] <support@github.com>

* Refactor: remove flow if there is no changes

* update group node function to reconnect edges when create groupNode

* Remove console.log statements

* Fix disallowed_special parameter in OpenAIEmbeddingsComponent

* Refactor CharacterTextSplitterComponent to use typing and update return value

* Update ChromaComponent configuration

* Bump version to 0.6.7a1 in pyproject.toml

* Add icon support to CustomComponent

* Add icon property to APIClassType

* Add emoji validation to icon field in custom components

* add emoji icon

* Fix: Error: cannot import name 'CreateTrace' from 'langfuse.callback'

* Refactor langflow processing and langfuse callback initialization

* Update version to 0.6.7a2 in pyproject.toml

* Fix: Bring back loading to avoid white page error

* Add dependabot.yml

* Bump actions/checkout from 2 to 4

Bumps [actions/checkout](https://github.com/actions/checkout) from 2 to 4.
- [Release notes](https://github.com/actions/checkout/releases)
- [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/checkout/compare/v2...v4)

---
updated-dependencies:
- dependency-name: actions/checkout
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump github/codeql-action from 2 to 3

Bumps [github/codeql-action](https://github.com/github/codeql-action) from 2 to 3.
- [Release notes](https://github.com/github/codeql-action/releases)
- [Changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md)
- [Commits](https://github.com/github/codeql-action/compare/v2...v3)

---
updated-dependencies:
- dependency-name: github/codeql-action
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump actions/setup-python from 4 to 5

Bumps [actions/setup-python](https://github.com/actions/setup-python) from 4 to 5.
- [Release notes](https://github.com/actions/setup-python/releases)
- [Commits](https://github.com/actions/setup-python/compare/v4...v5)

---
updated-dependencies:
- dependency-name: actions/setup-python
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump actions/cache from 2 to 4

Bumps [actions/cache](https://github.com/actions/cache) from 2 to 4.
- [Release notes](https://github.com/actions/cache/releases)
- [Changelog](https://github.com/actions/cache/blob/main/RELEASES.md)
- [Commits](https://github.com/actions/cache/compare/v2...v4)

---
updated-dependencies:
- dependency-name: actions/cache
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump actions/setup-node from 3 to 4

Bumps [actions/setup-node](https://github.com/actions/setup-node) from 3 to 4.
- [Release notes](https://github.com/actions/setup-node/releases)
- [Commits](https://github.com/actions/setup-node/compare/v3...v4)

---
updated-dependencies:
- dependency-name: actions/setup-node
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* makes function args not to be sorted by name

* Add field_order property to CustomComponent

* Refactor Template class in base.py

* Update field_order to be an optional list

* Refactor custom component field ordering

* Update prompts.mdx

Update broken link to all page building to complete

* add icon regex

* add isEmoji

* Fix invalid emoji error handling

* Fix invalid emoji validation in Component class

* add logic to icon name

* changing to useCallback function

* Add HuggingFaceInferenceAPIEmbeddingsComponent class

* Update QdrantComponent build method to handle pre-existing vector-stores

* Update python-multipart version

* Update dependencies in pyproject.toml

* Add Python 3.11 support to lint and test workflows

* Refactor import statements in Qdrant.py

* Update dependencies in pyproject.toml

* Fix documentation link and code formatting

* Fix validation of icon field in Component class

* Update imports and deactivate test

* Fixed group nodes appearing at tooltip

* Update imports and type annotations in several components

* Remove Python 3.9 from matrix in test.yml

* refactor: icon fragments functions

* Default display_name to None

* 🔧 chore(base.py): update serialize_display_name method to handle cases where display_name is not set and convert name to title case if title_case is True

* Fix error handling and formatting in component.py and typesStore.ts

* add controlX feature

* Add files via upload

* Fixed groupByFamily

* Add LiteLLMComponent to the project

* Add ChatLiteLLM component to backend

* Update ChatLiteLLM import and add verbose option

* Remove unused code in ChatLiteLLM.py

* Rename LiteLLMComponent to ChatLiteLLMComponent

* Changes some parameters for mypy linting compatibility

* Update cookie settings for login and refresh_token functions

* Update cookie settings for secure access

* Update cookie settings for login and token refresh

* Refactor authentication cookie settings

* Update version to 0.6.7a3 in pyproject.toml

* Fix formatting and import issues

* Import litellm package and update ChatLiteLLMComponent class

* Update version to 0.6.7a3 and fix formatting and import issues (#1445)

* Update version to 0.6.7a3 in pyproject.toml

* Fix formatting and import issues

* Import litellm package and update ChatLiteLLMComponent class

* Update login.py with new auth settings

* Update version to 0.6.7a4 in pyproject.toml

* Update version to 0.6.7a5 in pyproject.toml

* Update Langflow README (#1456)

* Update Langflow README

* Refactor flow creation process

* Update README.md

* Removed some phrases, changed Creating Flows section

* Update README.md with additional project references

---------

Co-authored-by: Gabriel Luiz Freitas Almeida <gabriel@logspace.ai>

* Add docs for field update, icon, and small fixes (#1459)

* Refactor code formatting and improve error handling in utils.py

* Refactor parameterComponent to include refresh button

* Update Langflow description

* Add new_langflow_demo.gif and remove langflow-demo.gif and langflow-screen.png

* Update image source path in README.md

* Add dynamic options and default value support to CustomComponent class

* Update version number in pyproject.toml

* Add title_case option to CustomComponent

* Refactor HuggingFaceEndpointsComponent imports and handle model_kwargs parameter

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: YoungWook KIM <ukng1024@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: igorrCarvalho <igorsilvabhz6@gmail.com>
Co-authored-by: anovazzi1 <otavio2204@gmail.com>
Co-authored-by: Cristhian Zanforlin Lousa <72977554+Cristhianzl@users.noreply.github.com>
Co-authored-by: cristhianzl <cristhian.lousa@gmail.com>
Co-authored-by: Łukasz Gajownik <lukasz.gajownik@ordergroup.pl>
Co-authored-by: Chris Bateman <chris-bateman@users.noreply.github.com>
Co-authored-by: Ricardo Henriques <paxcalpt@gmail.com>
Co-authored-by: Lucas Oliveira <lucas.edu.oli@hotmail.com>
Co-authored-by: Carlos Coelho <80289056+carlosrcoelho@users.noreply.github.com>
Co-authored-by: Lucas Oliveira <62335616+lucaseduoli@users.noreply.github.com>